### PR TITLE
Fix minor Linux build issues.  Resolves #28.

### LINKED ISSUE #28: Minor Linux build issues
There are case-sensitive filename mismatches in the CMake file:
3rdParty should be "3rdparty" and "Config.h" should be "config.h".

gcc 9.4 rejects using the same name for an enum class and a corresponding struct member:
GDeflateDemo/main.cpp:62:15: error: declaration of ‘Operation Options::Operation’ changes meaning of ‘Operation’ 

I will submit a pull request that fixes these.

### PR DESCRIPTION
**Pull request by MarkLeone**
- Case sensitive filename mismatch.
- Using same name for enum class and struct member.

### CODE REVIEW

**Comment by MarkLeone** [comment]
@microsoft-github-policy-service agree

File: GDeflate/GDeflateDemo/main.cpp [hunk 1]
```diff
@@ -59,7 +59,7 @@ enum class Operation
 struct Options
 {
     bool ShowHelp = false;
-    Operation Operation = Operation::None;
+    enum Operation Operation = Operation::None;
```
Comment (damyanp) [inline GDeflate/GDeflateDemo/main.cpp:62]: Thanks for this.  TBH, I'd prefer to see the enum name changed (or the field changed, but I can think of a new name for the enum - say "OperationType" - more easily than a new name for the field) rather than use the enum qualifier here.

**Review by damyanp — CHANGES_REQUESTED** [review]

File: GDeflate/GDeflateDemo/main.cpp (hunk 1 above)
Comment (MarkLeone) [reply GDeflate/GDeflateDemo/main.cpp]: Sure, I've updated the commit (force pushed to my fork).

**Review by damyanp — APPROVED** [review]

File: GDeflate/GDeflateDemo/main.cpp (hunk 1 above)
Comment (damyanp) [reply GDeflate/GDeflateDemo/main.cpp]: Thank you!

**Comment by damyanp** [comment]
Thank you for finding and fixing this!
